export interface ChartItem {
  title: string;
  href: string;
}

export interface NavItem {
  label: string;
  href: string;
  children?: { label: string; href: string }[];
}

export const CHART_ITEMS: ChartItem[] = [
  { title: "折線圖", href: "/line-chart-creation" },
  { title: "縱向 柱狀圖", href: "/vertical-bar-chart-creation" },
  { title: "基礎 餅圖", href: "/basic-pie-chart-creation" },
  { title: "散點圖", href: "/scatter-plot-creation" },
  { title: "K 線圖", href: "/k-line-chart-creation" },
  { title: "雷達圖", href: "/radar-chart-creation" },
  { title: "盒須圖", href: "/basic-boxplot-chart-creation" },
  { title: "樹狀圖", href: "/tree-chart-creation" },
  { title: "矩形樹圖", href: "/treemap-chart-creation" },
  { title: "旭日圖", href: "/sunburst-chart-creation" },
  { title: "桑基圖", href: "/sankey-chart-creation" },
  { title: "漏斗圖", href: "/funnel-chart-creation" },
  { title: "熱力圖", href: "/heatmap-cartesian-chart-creation" },
  { title: "直方圖", href: "/scatter-histogram-chart-creation" },
  { title: "基礎 儀錶盤圖", href: "/basic-dashboard-chart-creation" },
  { title: "主題河流圖", href: "/theme-river-basic-chart-creation" },
  { title: "半環形圖", href: "/semi-circular-pie-chart-creation" },
  { title: "南丁格爾玫瑰圖", href: "/nightingale-rose-chart-creation" },
  { title: "疊加對比 漏斗圖", href: "/stacked-contrast-funnel-chart-creation" },
  { title: "疊靠 漏斗圖", href: "/stacked-leaning-funnel-chart-creation" },
  { title: "另類 餅圖", href: "/alternative-pie-chart-creator" },
  { title: "圓角 環形圖", href: "/rounded-corner-circle-chart-creation" },
  { title: "縱向 盒須圖", href: "/vertical-boxplot-chart-creation" },
  { title: "基礎堆疊 條形圖", href: "/basic-stacked-bar-chart-creation" },
  { title: "堆疊 柱狀圖", href: "/bar-stack-brush-creation" },
  { title: "基礎堆疊歸一化百分比 條形圖", href: "/basic-stacked-bar-chart-normalized-percentage" },
  { title: "基礎 環形圖", href: "/basic-ring-chart-creation" },
  { title: "嵌套 環形圖", href: "/pie-nest-chart-creation" },
  { title: "扇區間隙 餅圖", href: "/sector-gap-pie-chart-creation" },
  { title: "折柱混合圖", href: "/mix-line-bar-chart-creation" },
  { title: "多 Y 軸 折柱混合圖", href: "/multi-yaxis-mix-line-bar-chart-creation" },
  { title: "極坐標 柱狀圖", href: "/bar-polar-chart-creation" },
  { title: "極坐標 圓角環形圖", href: "/polar-roundcap-chart-creation" },
  { title: "極坐標堆疊 柱狀圖", href: "/bar-polar-stack-chart-creation" },
  { title: "橫向 柱狀圖", href: "/horizontal-bar-chart-creation" },
  { title: "瀑布圖", href: "/waterfall-chart-creation" },
  { title: "縱向堆疊 條形圖", href: "/vertical-stacked-bar-chart-creation" },
  { title: "縱向堆疊歸一化百分比 條形圖", href: "/vertical-stacked-bar-chart-normalized-percentage" },
  { title: "詞雲圖", href: "/word-cloud-chart-creation" },
  { title: "進度 儀錶盤圖", href: "/progress-dashboard-chart-creation" },
  { title: "階梯 瀑布圖", href: "/step-waterfall-chart-creation" },
  { title: "餅圖聯動 折線圖", href: "/pie-linkage-line-chart-creation" },
  { title: "多 X 軸 折線圖", href: "/multi-xaxis-mix-line-bar-chart-creation" },
  { title: "垂直 折線圖", href: "/vertical-line-chart-creation" },
  { title: "凹凸圖/排序圖", href: "/bump-chart-creation" },
  { title: "極坐標 氣泡圖", href: "/scatter-polar-creation" },
  { title: "笛卡爾坐標 氣泡圖", href: "/cartesian-scatterplot-creation" },
  { title: "單軸 散點圖", href: "/scatter-single-axis-creation" },
  { title: "數據聚合 散點圖", href: "/data-aggregation-scatterplot-creation" },
  { title: "分布範圍 散點圖", href: "/scatterplot-distribution-ranges-creation" },
  { title: "多系列 盒須圖", href: "/multi-boxplot-creation" },
  { title: "函數繪製圖形", href: "/line-function-chart-creation" },
  { title: "帶標記/標線的 柱狀圖", href: "/bar-markpoint-markline-creation" },
  { title: "多數值 軸軸縮放 柱狀圖", href: "/mix-zoom-on-value-bar-creation" },
  { title: "可拖拽點的 折線圖", href: "/line-draggable-chart-creation" },
  { title: "可添加拐點的 折線圖", href: "/line-pen-chart-creation" },
  { title: "極坐標 雙數值軸 折線圖", href: "/line-polar-chart-creation" },
  { title: "極坐標 雙數值軸 折線圖-2", href: "/line-polar-chart-creation2" },
  { title: "雙數值軸 折線圖", href: "/line-in-cartesian-coordinate-system" },
  { title: "帶標記/標線的 折線圖", href: "/line-markpoint-markline-creation" },
  { title: "極坐標 熱力圖", href: "/polar-heatmap-chart-creation" },
  { title: "思維導圖", href: "/mind-mapping" },
  { title: "手寫白板畫布", href: "/whiteboard-canvas" },
  { title: "流程圖、矢量圖", href: "/online-flowchart-drawing2" },
  { title: "日曆圖", href: "/calendar-simple-chart-creation" },
  { title: "橫向 日曆圖", href: "/calendar-horizontal-chart-creation" },
  { title: "縱向 日曆圖", href: "/calendar-vertical-chart-creation" },
  { title: "圖片轉 3D柱狀圖", href: "/image-to-bar3d" },
  { title: "圖片轉 3D曲面圖", href: "/image-surface-sushuang" },
  { title: "3D 折線圖", href: "/line3d-chart-creation" },
  { title: "3D 柱狀圖", href: "/bar3d-chart-creation" },
  { title: "3D 曲面圖", href: "/3dsurface-chart-creation" },
  { title: "3D 散點圖", href: "/scatter3d-dataset-chart-creation" },
  { title: "虛線柱狀圖", href: "/pictorialbar-dotted-chart-creation" },
  { title: "氣泡圖", href: "/bubble-chart-creation" },
  { title: "氣泡圖2", href: "/bubble-chart-creation2" },
  { title: "AQI 氣泡圖", href: "/scatter-aqi-chart-creation" },
  { title: "流式渲染散點圖", href: "/scatter-stream-visual-chart-creation" },
  { title: "數據集 3D 柱狀圖", href: "/bar3d-dataset-chart-creation" },
  { title: "3D 體素化圖像", href: "/bar3d-voxelize-image" },
  { title: "3D 星雲效果", href: "/bar3d-myth-creation" },
  { title: "標籤右部對齊 散點圖", href: "/scatter-label-right" },
  { title: "標籤頂部對齊 散點圖", href: "/scatter-label-top" },
  { title: "時鐘屏保", href: "/clock-screensaver" },
];

export const NAV_ITEMS = [
  { label: "金融理財", href: "https://www.hasgg.com/financial-management" },
  { label: "數據圖表", href: "https://www.hasgg.com/data-chart" },
  { label: "單位換算", href: "https://www.hasgg.com/unit-conversion" },
  { label: "地理坐標", href: "https://www.hasgg.com/geographic-coordinates" },
  { label: "文檔辦公", href: "https://www.hasgg.com/document-office" },
  { label: "文本處理", href: "https://www.hasgg.com/text-processing" },
  { label: "站長開發", href: "https://www.hasgg.com/webmaster-development" },
  { label: "圖片處理", href: "https://www.hasgg.com/image-processing" },
  { label: "日常生活", href: "https://www.hasgg.com/daily-life" },
  { label: "命理運勢", href: "https://www.hasgg.com/numerology-horoscope" },
];