export interface ChartItem {
  title: string;
  href: string;
}

export interface NavItem {
  label: string;
  href: string;
  children?: { label: string; href: string }[];
}

export const CHART_ITEMS: ChartItem[] = [
  { title: "折線圖", href: "https://www.hasgg.com/line-chart-creation" },
  { title: "縱向 柱狀圖", href: "https://www.hasgg.com/vertical-bar-chart-creation" },
  { title: "基礎 餅圖", href: "https://www.hasgg.com/basic-pie-chart-creation" },
  { title: "散點圖", href: "https://www.hasgg.com/scatter-plot-creation" },
  { title: "K 線圖", href: "https://www.hasgg.com/k-line-chart-creation" },
  { title: "雷達圖", href: "https://www.hasgg.com/radar-chart-creation" },
  { title: "盒須圖", href: "https://www.hasgg.com/basic-boxplot-chart-creation" },
  { title: "樹狀圖", href: "https://www.hasgg.com/tree-chart-creation" },
  { title: "矩形樹圖", href: "https://www.hasgg.com/treemap-chart-creation" },
  { title: "旭日圖", href: "https://www.hasgg.com/sunburst-chart-creation" },
  { title: "桑基圖", href: "https://www.hasgg.com/sankey-chart-creation" },
  { title: "漏斗圖", href: "https://www.hasgg.com/funnel-chart-creation" },
  { title: "熱力圖", href: "https://www.hasgg.com/heatmap-cartesian-chart-creation" },
  { title: "直方圖", href: "https://www.hasgg.com/scatter-histogram-chart-creation" },
  { title: "基礎 儀錶盤圖", href: "https://www.hasgg.com/basic-dashboard-chart-creation" },
  { title: "主題河流圖", href: "https://www.hasgg.com/theme-river-basic-chart-creation" },
  { title: "半環形圖", href: "https://www.hasgg.com/semi-circular-pie-chart-creation" },
  { title: "南丁格爾玫瑰圖", href: "https://www.hasgg.com/nightingale-rose-chart-creation" },
  { title: "疊加對比 漏斗圖", href: "https://www.hasgg.com/stacked-contrast-funnel-chart-creation" },
  { title: "疊靠 漏斗圖", href: "https://www.hasgg.com/stacked-leaning-funnel-chart-creation" },
  { title: "另類 餅圖", href: "https://www.hasgg.com/alternative-pie-chart-creator" },
  { title: "圓角 環形圖", href: "https://www.hasgg.com/rounded-corner-circle-chart-creation" },
  { title: "縱向 盒須圖", href: "https://www.hasgg.com/vertical-boxplot-chart-creation" },
  { title: "基礎堆疊 條形圖", href: "https://www.hasgg.com/basic-stacked-bar-chart-creation" },
  { title: "堆疊 柱狀圖", href: "https://www.hasgg.com/bar-stack-brush-creation" },
  { title: "基礎堆疊歸一化百分比 條形圖", href: "https://www.hasgg.com/basic-stacked-bar-chart-normalized-percentage" },
  { title: "基礎 環形圖", href: "https://www.hasgg.com/basic-ring-chart-creation" },
  { title: "嵌套 環形圖", href: "https://www.hasgg.com/pie-nest-chart-creation" },
  { title: "扇區間隙 餅圖", href: "https://www.hasgg.com/sector-gap-pie-chart-creation" },
  { title: "折柱混合圖", href: "https://www.hasgg.com/mix-line-bar-chart-creation" },
  { title: "多 Y 軸 折柱混合圖", href: "https://www.hasgg.com/multi-yaxis-mix-line-bar-chart-creation" },
  { title: "極坐標 柱狀圖", href: "https://www.hasgg.com/bar-polar-chart-creation" },
  { title: "極坐標 圓角環形圖", href: "https://www.hasgg.com/polar-roundcap-chart-creation" },
  { title: "極坐標堆疊 柱狀圖", href: "https://www.hasgg.com/bar-polar-stack-chart-creation" },
  { title: "橫向 柱狀圖", href: "https://www.hasgg.com/horizontal-bar-chart-creation" },
  { title: "瀑布圖", href: "https://www.hasgg.com/waterfall-chart-creation" },
  { title: "縱向堆疊 條形圖", href: "https://www.hasgg.com/vertical-stacked-bar-chart-creation" },
  { title: "縱向堆疊歸一化百分比 條形圖", href: "https://www.hasgg.com/vertical-stacked-bar-chart-normalized-percentage" },
  { title: "詞雲圖", href: "https://www.hasgg.com/word-cloud-chart-creation" },
  { title: "進度 儀錶盤圖", href: "https://www.hasgg.com/progress-dashboard-chart-creation" },
  { title: "階梯 瀑布圖", href: "https://www.hasgg.com/step-waterfall-chart-creation" },
  { title: "餅圖聯動 折線圖", href: "https://www.hasgg.com/pie-linkage-line-chart-creation" },
  { title: "多 X 軸 折線圖", href: "https://www.hasgg.com/multi-xaxis-mix-line-bar-chart-creation" },
  { title: "垂直 折線圖", href: "https://www.hasgg.com/vertical-line-chart-creation" },
  { title: "凹凸圖/排序圖", href: "https://www.hasgg.com/bump-chart-creation" },
  { title: "極坐標 氣泡圖", href: "https://www.hasgg.com/scatter-polar-creation" },
  { title: "笛卡爾坐標 氣泡圖", href: "https://www.hasgg.com/cartesian-scatterplot-creation" },
  { title: "單軸 散點圖", href: "https://www.hasgg.com/scatter-single-axis-creation" },
  { title: "數據聚合 散點圖", href: "https://www.hasgg.com/data-aggregation-scatterplot-creation" },
  { title: "分布範圍 散點圖", href: "https://www.hasgg.com/scatterplot-distribution-ranges-creation" },
  { title: "多系列 盒須圖", href: "https://www.hasgg.com/multi-boxplot-creation" },
  { title: "函數繪製圖形", href: "https://www.hasgg.com/line-function-chart-creation" },
  { title: "帶標記/標線的 柱狀圖", href: "https://www.hasgg.com/bar-markpoint-markline-creation" },
  { title: "多數值 軸軸縮放 柱狀圖", href: "https://www.hasgg.com/mix-zoom-on-value-bar-creation" },
  { title: "可拖拽點的 折線圖", href: "https://www.hasgg.com/line-draggable-chart-creation" },
  { title: "可添加拐點的 折線圖", href: "https://www.hasgg.com/line-pen-chart-creation" },
  { title: "極坐標 雙數值軸 折線圖", href: "https://www.hasgg.com/line-polar-chart-creation" },
  { title: "極坐標 雙數值軸 折線圖-2", href: "https://www.hasgg.com/line-polar-chart-creation2" },
  { title: "雙數值軸 折線圖", href: "https://www.hasgg.com/line-in-cartesian-coordinate-system" },
  { title: "帶標記/標線的 折線圖", href: "https://www.hasgg.com/line-markpoint-markline-creation" },
  { title: "極坐標 熱力圖", href: "https://www.hasgg.com/polar-heatmap-chart-creation" },
  { title: "思維導圖", href: "https://www.hasgg.com/mind-mapping" },
  { title: "手寫白板畫布", href: "https://www.hasgg.com/whiteboard-canvas" },
  { title: "流程圖、矢量圖", href: "https://www.hasgg.com/online-flowchart-drawing2" },
  { title: "日曆圖", href: "https://www.hasgg.com/calendar-simple-chart-creation" },
  { title: "橫向 日曆圖", href: "https://www.hasgg.com/calendar-horizontal-chart-creation" },
  { title: "縱向 日曆圖", href: "https://www.hasgg.com/calendar-vertical-chart-creation" },
  { title: "圖片轉 3D柱狀圖", href: "https://www.hasgg.com/image-to-bar3d" },
  { title: "圖片轉 3D曲面圖", href: "https://www.hasgg.com/image-surface-sushuang" },
  { title: "3D 折線圖", href: "https://www.hasgg.com/line3d-chart-creation" },
  { title: "3D 柱狀圖", href: "https://www.hasgg.com/bar3d-chart-creation" },
  { title: "3D 曲面圖", href: "https://www.hasgg.com/3dsurface-chart-creation" },
  { title: "3D 散點圖", href: "https://www.hasgg.com/scatter3d-dataset-chart-creation" },
  { title: "虛線柱狀圖", href: "https://www.hasgg.com/pictorialbar-dotted-chart-creation" },
  { title: "氣泡圖", href: "https://www.hasgg.com/bubble-chart-creation" },
  { title: "氣泡圖2", href: "https://www.hasgg.com/bubble-chart-creation2" },
  { title: "AQI 氣泡圖", href: "https://www.hasgg.com/scatter-aqi-chart-creation" },
  { title: "流式渲染散點圖", href: "https://www.hasgg.com/scatter-stream-visual-chart-creation" },
  { title: "數據集 3D 柱狀圖", href: "https://www.hasgg.com/bar3d-dataset-chart-creation" },
  { title: "3D 體素化圖像", href: "https://www.hasgg.com/bar3d-voxelize-image" },
  { title: "3D 星雲效果", href: "https://www.hasgg.com/bar3d-myth-creation" },
  { title: "標籤右部對齊 散點圖", href: "https://www.hasgg.com/scatter-label-right" },
  { title: "標籤頂部對齊 散點圖", href: "https://www.hasgg.com/scatter-label-top" },
  { title: "時鐘屏保", href: "https://www.hasgg.com/clock-screensaver" },
];

export const NAV_ITEMS = [
  { label: "金融理財", href: "https://www.hasgg.com/financial-management" },
  { label: "數據圖表", href: "https://www.hasgg.com/data-chart" },
  { label: "單位換算", href: "https://www.hasgg.com/unit-conversion" },
  { label: "地理坐標", href: "https://www.hasgg.com/geographic-coordinates" },
  { label: "文檔辦公", href: "https://www.hasgg.com/document-office" },
  { label: "文本處理", href: "https://www.hasgg.com/text-processing" },
  { label: "站長開發", href: "https://www.hasgg.com/webmaster-development" },
  { label: "圖片處理", href: "https://www.hasgg.com/image-processing" },
  { label: "日常生活", href: "https://www.hasgg.com/daily-life" },
  { label: "命理運勢", href: "https://www.hasgg.com/numerology-horoscope" },
];